name: MarioKart
main: net.stormdev.mario.mariokart.MarioKart
version: 6.2
softdepend: [Vault, BarAPI]
depend: [uCars]
commands:
   marioRaceAdmin:
        aliases: [mra, marioadmin]
        description: This is the setup of racetracks and admin commands
        usage: /<command> [Create <TrackName> <Laps> (MinPlayers)] [Delete <TrackName>] [List (Page)] [Races (Page)] [End <RaceTrack>/Endall] [setLaps <TrackName> <Laps>] [setMinPlayers <TrackName> <Num>] [setRewards <TrackName> <1st> <2nd> <3rd>] [ShopVillager]
        permission: mariokart.raceadmin
        permission-message: You don't have access to this command
        default: op
   race:
        description: This is the playing of race tracks
        usage: /<command> [List (Page)] [Join <Track> (GameType "Race"/"Timed"/"Cup")] [Leave] [Queues] [Shop]
        permission: mariokart.race
        permission-message: You don't have access to this command
        default: true
   racetimes:
        description: Shows the top X race times for a track.
        usage: /<command> <TrackName> <Amount>
        permission: mariokart.race
        permission-message: You don't have access to this command
        default: true
   vote:
        description: Vote for a track
        usage: /<command> <TrackName>