name: MarioKart
main: net.stormdev.ucars.race.main
version: 2.1
softdepend: [Vault]
depend: [uCars]
commands:
   marioRaceAdmin:
        aliases: [mra, marioadmin]
        description: This is the setup of racetracks and admin commands
        usage: /<command> [Create <TrackName> <Laps>] [Delete <TrackName>] [List (Page)] [setLaps <TrackName> <Laps>]
        permission: mariokart.raceadmin
        permission-message: You don't have access to this command
        default: op
   race:
        description: This is the playing of race tracks
        usage: /<command> [List (Page)] [Join <Track>] [Leave] [Queues]
        permission: mariokart.race
        permission-message: You don't have access to this command
        default: true